
spring:
  profiles:
    active: dev
  mail:
    host: smtp.gmail.com
    port: 584
    test-connection: true

  sql:
    init:
      mode: always
  threads:
    virtual:
      enabled: true

server:
  http2:
    enabled: true
  port: 9080
  error:
    include-binding-errors: never
    include-exception: false
    include-stacktrace: never

resilience4j:
  ratelimiter:
    configs:
      default:
        limit-for-period: 1
        limit-refresh-period:
          seconds: 60
        timeout-duration:
          seconds: 30
    instances:
      limitA:
        base-config: default
