spring:
  config:
    import: optional:credentials.yaml

  datasource:
    url: jdbc:postgresql://localhost:5432/authorization_server
  mail:
    host: smtp.gmail.com
    port: 584
    test-connection: true

